/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ittol.is.automatas.lexi.gui;

import edu.ittol.is.automatas.lexi.core.AutomataEngine;

/**
 *
 * @author julia
 */
public class AutomatonUI extends javax.swing.JFrame
{

    private AutomataEngine engine;

    /**
     * Creates new form AutomatonUI
     */
    public AutomatonUI(AutomataEngine engine)
    {
        initComponents();
        this.engine = engine;
        // Ahora simplemente arrastra un JLabel en el diseño gráfico (Matisse), 
        // haz clic derecho -> Properties -> icon -> Import to Project... y selecciona tu imagen manualmente.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblAutomatonView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autómata");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(450, 380));
        setName("AutomatonForm"); // NOI18N
        setPreferredSize(new java.awt.Dimension(450, 380));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        lblAutomatonView.setBackground(new java.awt.Color(255, 51, 102));
        lblAutomatonView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/automata-finito-det.jff.png"))); // NOI18N
        lblAutomatonView.setMaximumSize(new java.awt.Dimension(400, 300));
        lblAutomatonView.setMinimumSize(new java.awt.Dimension(400, 300));
        lblAutomatonView.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(lblAutomatonView, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAutomatonView;
    // End of variables declaration//GEN-END:variables
}
