/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ittol.is.automatas.lexi.gui;

import edu.ittol.is.automatas.lexi.core.AutomataEngine;

/**
 *
 * @author julia
 */
public class AutomatonUI extends javax.swing.JFrame
{

    private AutomataEngine engine;

    /**
     * Creates new form AutomatonUI
     */
    public AutomatonUI(AutomataEngine engine)
    {
        initComponents();
        this.engine = engine;
        init();
    }

    public void init()
    {
        int width = this.getPreferredSize().width;
        int height = this.getPreferredSize().height;
        try
        {
            String apiURL = engine.getAutomatonImageUrl();
            System.out.println("Cargando imagen desde: " + apiURL);
            
            // Requerido: Forzar User-Agent para que el API no prohíba descargas automáticas de Java
            java.net.URLConnection connection = new java.net.URL(apiURL).openConnection();
            connection.setRequestProperty("User-Agent", "Mozilla/5.0");
            
            // Java descarga velozmente la imagen del grafo renderizada y la carga en memoria
            java.awt.image.BufferedImage img = javax.imageio.ImageIO.read(connection.getInputStream());

            if (img != null) {
                // Escalar localmente al tamaño de 400x300 usando un algoritmo suave para evitar pixeleo
                java.awt.Image imagenEscalada = img.getScaledInstance(width-40, height-40, java.awt.Image.SCALE_SMOOTH);

                // Asignar al JLabel
                lblAutomatonView.setIcon(new javax.swing.ImageIcon(imagenEscalada));
                lblAutomatonView.setText("");
                lblAutomatonView.revalidate();
                lblAutomatonView.repaint();
            } else {
                System.out.println("Error: Quickchart regresó nulo (formato ilegible).");
            }

        } catch (Exception e)
        {
            System.out.println("Error al obtener la gráfica: requiere conexión a internet.");
            System.out.println(e.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblAutomatonView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Autómata");
        setAlwaysOnTop(true);
        setName("AutomatonForm"); // NOI18N
        setPreferredSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        lblAutomatonView.setBackground(new java.awt.Color(255, 51, 102));
        lblAutomatonView.setMaximumSize(new java.awt.Dimension(400, 300));
        lblAutomatonView.setMinimumSize(new java.awt.Dimension(400, 300));
        lblAutomatonView.setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().add(lblAutomatonView, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblAutomatonView;
    // End of variables declaration//GEN-END:variables
}
