package edu.ittol.is.automatas.lexi.gui;

import edu.ittol.is.automatas.lexi.core.AutomataEngine;
import edu.ittol.is.automatas.lexi.utils.ValidationUtils;
import java.awt.Color;

public class LexiUI extends javax.swing.JFrame
{

    private AutomataEngine engine;

    /**
     * Creates new form LexiUI
     */
    public LexiUI(AutomataEngine engine)
    {
        initComponents();
        this.engine = engine;
    }

    private void setWarning(String textWarning)
    {
        panValidate.setBackground(Color.yellow);
        lblValidate.setForeground(Color.black);
        lblValidate.setText(textWarning);
    }

    private void setValidate()
    {
        panValidate.setBackground(Color.green);
        lblValidate.setForeground(Color.white);
        lblValidate.setText("Cadena Válida");
    }

    private void setInvalidate()
    {
        panValidate.setBackground(Color.red);
        lblValidate.setForeground(Color.white);
        lblValidate.setText("Cadena No Válida");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtString = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        panValidate = new javax.swing.JPanel();
        lblValidate = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("mainFrame"); // NOI18N
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jPanel1.setFocusable(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setFocusable(false);
        jPanel2.setMaximumSize(new java.awt.Dimension(32767, 120));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 100));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        jPanel6.setFocusable(false);
        jPanel6.setMaximumSize(new java.awt.Dimension(370, 50));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Ingresa una cadena:");
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel3.setFocusable(false);
        jPanel3.setMaximumSize(new java.awt.Dimension(370, 30));
        jPanel3.setMinimumSize(new java.awt.Dimension(370, 0));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(370, 30));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        txtString.setText("jTextField1");
        txtString.setToolTipText("Ingresa una cadena para validar...");
        txtString.setMaximumSize(new java.awt.Dimension(400, 100));
        txtString.setMinimumSize(new java.awt.Dimension(0, 0));
        txtString.setName("txtString"); // NOI18N
        txtString.setPreferredSize(new java.awt.Dimension(400, 100));
        txtString.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                txtStringKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtStringKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt)
            {
                txtStringKeyTyped(evt);
            }
        });
        jPanel3.add(txtString);

        jPanel7.setMaximumSize(new java.awt.Dimension(10, 100));
        jPanel7.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);

        panValidate.setFocusable(false);
        panValidate.setMaximumSize(new java.awt.Dimension(200, 100));
        panValidate.setMinimumSize(new java.awt.Dimension(0, 0));
        panValidate.setName("panValidate"); // NOI18N
        panValidate.setPreferredSize(new java.awt.Dimension(200, 100));
        panValidate.setLayout(new java.awt.BorderLayout());

        lblValidate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidate.setText("Validate");
        lblValidate.setFocusable(false);
        lblValidate.setName("lblValidate"); // NOI18N
        panValidate.add(lblValidate, java.awt.BorderLayout.CENTER);

        jPanel3.add(panValidate);

        jPanel1.add(jPanel3);

        jPanel4.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStringKeyTyped(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtStringKeyTyped
    {//GEN-HEADEREND:event_txtStringKeyTyped

    }//GEN-LAST:event_txtStringKeyTyped

    private void txtStringKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtStringKeyPressed
    {//GEN-HEADEREND:event_txtStringKeyPressed

    }//GEN-LAST:event_txtStringKeyPressed

    private void txtStringKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtStringKeyReleased
    {//GEN-HEADEREND:event_txtStringKeyReleased
        String input = txtString.getText();
        System.out.println(input);
        if (!ValidationUtils.isStrictBinary(input))
        {
            setWarning("Caracteres no válidos");
            return;
        }

        boolean cadenaAceptada = engine.isValid(input);

        if (cadenaAceptada)
        {
            setValidate();
        } else
        {
            setInvalidate();
        }
    }//GEN-LAST:event_txtStringKeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblValidate;
    private javax.swing.JPanel panValidate;
    private javax.swing.JTextField txtString;
    // End of variables declaration//GEN-END:variables
}
