package edu.ittol.is.automatas.lexi.gui;

import edu.ittol.is.automatas.lexi.core.AutomataEngine;
import edu.ittol.is.automatas.lexi.utils.ValidationUtils;
import java.awt.Color;
import javax.swing.JOptionPane;

public class LexiUI extends javax.swing.JFrame
{

    private AutomataEngine engine;

    /**
     * Creates new form LexiUI
     */
    public LexiUI(AutomataEngine engine)
    {
        initComponents();
        this.engine = engine;
        txtStringKeyReleased(null);
    }

    private void setWarning(String textWarning)
    {
        panValidate.setBackground(new Color(148, 116, 12));
        lblValidate.setForeground(Color.white);
        lblValidate.setText(textWarning);
    }

    private void setValidate()
    {
        panValidate.setBackground(new Color(52, 92, 24));
        lblValidate.setForeground(Color.white);
        lblValidate.setText("Cadena Válida");
    }

    private void setInvalidate()
    {
        panValidate.setBackground(new Color(117, 9, 9));
        lblValidate.setForeground(Color.white);
        lblValidate.setText("Cadena No Válida");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtString = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        panValidate = new javax.swing.JPanel();
        lblValidate = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jMenuBar = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        btnGenerateValidString = new javax.swing.JMenuItem();
        btnViewRegEx = new javax.swing.JMenuItem();
        btnViewAutomaton = new javax.swing.JMenuItem();
        btnAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lexi");
        setName("mainFrame"); // NOI18N
        setResizable(false);

        jPanel1.setFocusable(false);
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel2.setFocusable(false);
        jPanel2.setMaximumSize(new java.awt.Dimension(400, 50));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);

        jPanel6.setFocusable(false);
        jPanel6.setMaximumSize(new java.awt.Dimension(370, 50));
        jPanel6.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.setPreferredSize(new java.awt.Dimension(300, 20));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Ingresa una cadena:");
        jLabel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel6.add(jLabel1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel3.setFocusable(false);
        jPanel3.setMaximumSize(new java.awt.Dimension(370, 30));
        jPanel3.setMinimumSize(new java.awt.Dimension(370, 0));
        jPanel3.setName(""); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(370, 30));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        txtString.setToolTipText("Ingresa una cadena para validar...");
        txtString.setMaximumSize(new java.awt.Dimension(400, 100));
        txtString.setMinimumSize(new java.awt.Dimension(0, 0));
        txtString.setName("txtString"); // NOI18N
        txtString.setPreferredSize(new java.awt.Dimension(300, 100));
        txtString.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtStringKeyReleased(evt);
            }
        });
        jPanel3.add(txtString);

        jPanel7.setMaximumSize(new java.awt.Dimension(10, 100));
        jPanel7.setPreferredSize(new java.awt.Dimension(10, 100));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 7, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        jPanel3.add(jPanel7);

        panValidate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 3));
        panValidate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panValidate.setFocusable(false);
        panValidate.setMaximumSize(new java.awt.Dimension(200, 100));
        panValidate.setMinimumSize(new java.awt.Dimension(0, 0));
        panValidate.setName("panValidate"); // NOI18N
        panValidate.setPreferredSize(new java.awt.Dimension(200, 100));
        panValidate.setLayout(new java.awt.BorderLayout());

        lblValidate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblValidate.setFocusable(false);
        lblValidate.setName("lblValidate"); // NOI18N
        panValidate.add(lblValidate, java.awt.BorderLayout.CENTER);

        jPanel3.add(panValidate);

        jPanel1.add(jPanel3);

        jPanel4.setFocusable(false);
        jPanel4.setMaximumSize(new java.awt.Dimension(400, 50));
        jPanel4.setPreferredSize(new java.awt.Dimension(400, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenu.setText("Opciones");

        btnGenerateValidString.setText("Generar Cadena Válida");
        btnGenerateValidString.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnGenerateValidStringActionPerformed(evt);
            }
        });
        jMenu.add(btnGenerateValidString);

        btnViewRegEx.setText("Ver Expresión Regular");
        btnViewRegEx.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnViewRegExActionPerformed(evt);
            }
        });
        jMenu.add(btnViewRegEx);

        btnViewAutomaton.setText("Ver Autómata");
        btnViewAutomaton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnViewAutomatonActionPerformed(evt);
            }
        });
        jMenu.add(btnViewAutomaton);

        btnAbout.setText("Acerca de / Ayuda");
        btnAbout.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAboutActionPerformed(evt);
            }
        });
        jMenu.add(btnAbout);

        jMenuBar.add(jMenu);

        setJMenuBar(jMenuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtStringKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtStringKeyReleased
    {//GEN-HEADEREND:event_txtStringKeyReleased
        String input = txtString.getText();
        if (!ValidationUtils.isStrictBinary(input))
        {
            setWarning("Caracteres no válidos");
            return;
        }

        boolean cadenaAceptada = engine.isValid(input);

        if (cadenaAceptada)
        {
            setValidate();
        } else
        {
            setInvalidate();
        }
    }//GEN-LAST:event_txtStringKeyReleased

    private void btnViewRegExActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnViewRegExActionPerformed
    {//GEN-HEADEREND:event_btnViewRegExActionPerformed
        JOptionPane.showMessageDialog(this, engine.getER(), "Expresión Regular", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnViewRegExActionPerformed

    private void btnGenerateValidStringActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnGenerateValidStringActionPerformed
    {//GEN-HEADEREND:event_btnGenerateValidStringActionPerformed
        String cadenaMinima = engine.getExample();
        txtString.setText(cadenaMinima);
        txtStringKeyReleased(null);
    }//GEN-LAST:event_btnGenerateValidStringActionPerformed

    private void btnViewAutomatonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnViewAutomatonActionPerformed
    {//GEN-HEADEREND:event_btnViewAutomatonActionPerformed
        AutomatonUI automatonForm = new AutomatonUI(this.engine);
        automatonForm.setVisible(true);
    }//GEN-LAST:event_btnViewAutomatonActionPerformed

    private void btnAboutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAboutActionPerformed
    {//GEN-HEADEREND:event_btnAboutActionPerformed
        String message = """
                         Este validador verifica las cadenas ingresadas cumplan con condiciones descritas de un lenguaje específico:
                         1. El alfabeto está compuesto por {0 , 1}.
                         2. Los últimos dos caracteres de la cadena sean exactamente '10'.
                             --- ó ---
                            Que termine con un '1' seguido de cualquier otro par de caracteres extra.""";
        
        JOptionPane.showMessageDialog(this, message, "¿Cómo funciona?", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnAboutActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnAbout;
    private javax.swing.JMenuItem btnGenerateValidString;
    private javax.swing.JMenuItem btnViewAutomaton;
    private javax.swing.JMenuItem btnViewRegEx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblValidate;
    private javax.swing.JPanel panValidate;
    private javax.swing.JTextField txtString;
    // End of variables declaration//GEN-END:variables
}
